/**
 * SpriteFactory — programmatic pixel-art assets for Missile Command Math
 * Generated by the Asset Creation Agent.
 * DO NOT hand-edit. Re-run the asset creation agent to regenerate.
 *
 * All color constants are taken directly from the visual style guide.
 * All dimensions match the Sprite Specifications table exactly.
 * All animation configs match the Animations table exactly.
 */
import Phaser from 'phaser';

// ---------------------------------------------------------------------------
// Color constants (from style guide Color Palette table)
// ---------------------------------------------------------------------------
const COLOR_BG                = '#C8B8DC';
const COLOR_PLAYFIELD         = '#E8E0F0';
const COLOR_CRT_BEZEL         = '#C8952A';
const COLOR_GROUND_LINE       = '#4A8A9A';
const COLOR_BUILDING_CORAL    = '#E8766A';
const COLOR_BUILDING_BLUE     = '#8BBDD9';
const COLOR_BUILDING_PEACH    = '#F2B89A';
const COLOR_WINDOW            = '#C8A84A';
const COLOR_SMOKE             = '#9A9A9A';
const COLOR_DEBRIS            = '#D96858';
const COLOR_EXPLOSION_CORE    = '#FFFAAA';
const COLOR_EXPLOSION_RAY     = '#F07020';
const COLOR_EXPLOSION_OUTER   = '#F0A000';
const COLOR_TRAIL             = '#C8A060';
const COLOR_BOMB_ORANGE       = '#E8701A';
const COLOR_BOMB_TEAL         = '#2D7A8C';
const COLOR_BOMB_MAGENTA      = '#A0306A';
const COLOR_BOMB_GOLD_BAND    = '#F0C030';
const COLOR_BOMB_OUTLINE      = '#4A2808';
const COLOR_LAUNCHER_ORANGE   = '#E8851A';
const COLOR_LAUNCHER_TEAL     = '#2D7A8C';
const COLOR_LAUNCHER_MAGENTA  = '#A0306A';
const COLOR_LAUNCHER_BADGE    = '#FFFFFF';
const COLOR_LAUNCHER_NUMBER   = '#C8A040';
const COLOR_PROJECTILE_BODY   = '#E03030';
const COLOR_PROJECTILE_BAND   = '#F0D020';
const COLOR_PROJECTILE_FIN    = '#3A90B0';
const COLOR_BOMBER_FUSELAGE   = '#7A8C4A';
const COLOR_BOMBER_WING       = '#C8A878';
const COLOR_BOMBER_TAIL       = '#D94040';
const COLOR_BOMBER_NACELLE    = '#E899A8';
const COLOR_BOMBER_COCKPIT    = '#A8D4E8';
const COLOR_BOMBER_OUTLINE    = '#4A2808';
const COLOR_HUD_TEXT          = '#C8952A';
const COLOR_HUD_BG            = '#C8B8DC';
const COLOR_MATH_TEXT         = '#E8701A';
const COLOR_WRONG_FLASH       = '#E03030';
const COLOR_CITY_CELEBRATE    = '#F0C030';

// Derived / utility colors
const COLOR_CRT_BEVEL_LIGHT   = '#E0B050';
const COLOR_CRT_BEVEL_DARK    = '#A07820';
const COLOR_CRACK             = '#2A1A0A';
const COLOR_CRANE_YELLOW      = '#F0C030';

// ---------------------------------------------------------------------------
// Sprite key constants — import these; never use raw strings
// ---------------------------------------------------------------------------
export const SPRITE_KEYS = {
  LAUNCHER_ORANGE:      'LAUNCHER_ORANGE',
  LAUNCHER_TEAL:        'LAUNCHER_TEAL',
  LAUNCHER_MAGENTA:     'LAUNCHER_MAGENTA',
  LAUNCHER_FLASH:       'LAUNCHER_FLASH',
  BOMB_ORANGE:          'BOMB_ORANGE',
  BOMB_TEAL:            'BOMB_TEAL',
  BOMB_MAGENTA:         'BOMB_MAGENTA',
  PROJECTILE:           'PROJECTILE',
  EXPLOSION:            'EXPLOSION',
  BUILDING_INTACT_A:    'BUILDING_INTACT_A',
  BUILDING_INTACT_B:    'BUILDING_INTACT_B',
  BUILDING_INTACT_C:    'BUILDING_INTACT_C',
  BUILDING_DAMAGED:     'BUILDING_DAMAGED',
  BUILDING_DESTROYED:   'BUILDING_DESTROYED',
  BOMBER:               'BOMBER',
  CRT_FRAME:            'CRT_FRAME',
  GROUND_LINE:          'GROUND_LINE',
  HUD_BAR:              'HUD_BAR',
  SCORE_POP:            'SCORE_POP',
  STREAK_BADGE:         'STREAK_BADGE',
  TRAJECTORY_TRAIL_DOT: 'TRAJECTORY_TRAIL_DOT',
  FIREWORK_BURST:       'FIREWORK_BURST',
  REBUILD_CRANE:        'REBUILD_CRANE',
} as const;

export type SpriteKey = typeof SPRITE_KEYS[keyof typeof SPRITE_KEYS];

// ---------------------------------------------------------------------------
// Animation key constants — import these; never use raw strings
// ---------------------------------------------------------------------------
export const ANIM_KEYS = {
  LAUNCHER_WRONG_FLASH: 'LAUNCHER_WRONG_FLASH',
  EXPLOSION_BURST:      'EXPLOSION_BURST',
  BUILDING_HIT:         'BUILDING_HIT',
  BOMBER_FLY:           'BOMBER_FLY',
  FIREWORK_POP:         'FIREWORK_POP',
  REBUILD_CRANE_LIFT:   'REBUILD_CRANE_LIFT',
} as const;

export type AnimKey = typeof ANIM_KEYS[keyof typeof ANIM_KEYS];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
function makeCanvas(w: number, h: number): HTMLCanvasElement {
  const c = document.createElement('canvas');
  c.width = w;
  c.height = h;
  return c;
}

function ctx2d(canvas: HTMLCanvasElement): CanvasRenderingContext2D {
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  return ctx;
}

/**
 * Draw a rounded rectangle path (does not stroke/fill — caller does that).
 */
function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number,
  r: number
): void {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.arcTo(x + w, y,     x + w, y + r,     r);
  ctx.lineTo(x + w, y + h - r);
  ctx.arcTo(x + w, y + h, x + w - r, y + h, r);
  ctx.lineTo(x + r, y + h);
  ctx.arcTo(x,     y + h, x,     y + h - r, r);
  ctx.lineTo(x,     y + r);
  ctx.arcTo(x,     y,     x + r, y,         r);
  ctx.closePath();
}

/**
 * Register a sprite sheet from an HTMLCanvasElement.
 *
 * Phaser 3's TextureManager.addSpriteSheet() accepts HTMLCanvasElement directly —
 * no intermediate CanvasTexture wrapper needed.
 */
function addSheetFromCanvas(
  scene: Phaser.Scene,
  key: string,
  canvas: HTMLCanvasElement,
  frameWidth: number,
  frameHeight: number,
): void {
  // Phaser 3 runtime accepts HTMLCanvasElement, but its TS types only declare
  // HTMLImageElement | Texture. Cast to bypass the stale type declaration.
  // Do NOT use the addCanvas→addSpriteSheet→remove pattern: remove() destroys
  // the canvas data that the new SpriteSheet texture depends on.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  scene.textures.addSpriteSheet(key, canvas as any, { frameWidth, frameHeight });
}

/**
 * Draw a launcher bell/bag silhouette into an existing canvas context.
 * The launcher is drawn at offset (ox, oy) within the canvas.
 * bodyColor — the fill for the launcher body.
 * This is the shared shape used by all three launcher variants.
 */
function drawLauncherShape(
  ctx: CanvasRenderingContext2D,
  ox: number, oy: number,
  bodyColor: string
): void {
  // --- Body: rounded bell / bag shape ---
  // Width 80px, height 90px.
  // The bag sits in the lower ~76px; nozzle occupies top 14px.
  const bx = ox;
  const by = oy;

  // Cast shadow: ellipse beneath base
  ctx.save();
  ctx.beginPath();
  ctx.ellipse(bx + 40, by + 88, 30, 6, 0, 0, Math.PI * 2);
  ctx.fillStyle = 'rgba(0,0,0,0.18)';
  ctx.fill();
  ctx.restore();

  // Nozzle: small cylinder on top-center, 12×14px
  ctx.save();
  roundRect(ctx, bx + 34, by, 12, 14, 3);
  ctx.fillStyle = bodyColor;
  ctx.fill();
  ctx.strokeStyle = COLOR_BOMB_OUTLINE;
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.restore();

  // Main bell body: rounded-bottom rect that tapers slightly
  // We approximate the bell with a rounded rect for the lower portion
  ctx.save();
  // Draw the bag body: wider at bottom, slightly narrower at top
  // Using a path that mimics a bell/bag silhouette
  ctx.beginPath();
  // Start from top-left of body (below nozzle, at y=12)
  const bodyTop = by + 12;
  const bodyBot = by + 86;
  const bodyLeft = bx + 4;
  const bodyRight = bx + 76;
  const bodyMidLeft = bx + 0;
  const bodyMidRight = bx + 80;
  const bodyMidY = by + 50;

  ctx.moveTo(bx + 30, bodyTop); // top-left shoulder
  ctx.lineTo(bx + 50, bodyTop); // top-right shoulder
  // Curve out to full width at mid
  ctx.bezierCurveTo(bx + 70, bodyTop + 4, bodyMidRight, bodyMidY - 10, bodyMidRight, bodyMidY);
  // Curve in at bottom
  ctx.bezierCurveTo(bodyMidRight, bodyMidY + 20, bodyRight, bodyBot - 6, bodyRight - 4, bodyBot);
  ctx.lineTo(bodyLeft + 4, bodyBot);
  ctx.bezierCurveTo(bodyLeft, bodyBot - 6, bodyMidLeft, bodyMidY + 20, bodyMidLeft, bodyMidY);
  ctx.bezierCurveTo(bodyMidLeft, bodyMidY - 10, bx + 10, bodyTop + 4, bx + 30, bodyTop);
  ctx.closePath();

  ctx.fillStyle = bodyColor;
  ctx.fill();
  ctx.strokeStyle = COLOR_BOMB_OUTLINE;
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.restore();

  // White oval badge centered on front face: 48×44px, centered at (40, 54)
  ctx.save();
  ctx.beginPath();
  ctx.ellipse(bx + 40, by + 54, 24, 22, 0, 0, Math.PI * 2);
  ctx.fillStyle = COLOR_LAUNCHER_BADGE;
  ctx.fill();
  ctx.strokeStyle = COLOR_BOMB_OUTLINE;
  ctx.lineWidth = 1.5;
  ctx.stroke();
  ctx.restore();
}

/**
 * Draw a bomb (elongated teardrop) shape.
 * bodyColor — fill color of the bomb body.
 * Canvas must be 36×64px (single frame).
 */
function drawBombShape(
  ctx: CanvasRenderingContext2D,
  ox: number, oy: number,
  bodyColor: string
): void {
  const cx = ox + 18; // horizontal center

  // Elongated teardrop: rounded nose at top, tapers to blunt point at bottom.
  // Width 36px at widest (~y=24), total height 64px.
  ctx.save();
  ctx.beginPath();
  // Top rounded nose
  ctx.arc(cx, oy + 18, 18, Math.PI, 0); // semicircle nose: y=0 to y=18
  // Right side curves down to bottom point
  ctx.bezierCurveTo(cx + 18, oy + 36, cx + 10, oy + 56, cx, oy + 64);
  // Left side back up
  ctx.bezierCurveTo(cx - 10, oy + 56, cx - 18, oy + 36, cx - 18, oy + 18);
  ctx.closePath();

  ctx.fillStyle = bodyColor;
  ctx.fill();
  ctx.strokeStyle = COLOR_BOMB_OUTLINE;
  ctx.lineWidth = 3;
  ctx.stroke();
  ctx.restore();

  // Gold band: 8px tall, 14px from top (y = oy+14 to oy+22), full width of bomb at that point
  // At y=14 the bomb radius is approx 14px (nearly full width), at y=22 it's ~18px
  ctx.save();
  // Clip to bomb shape so band doesn't overflow
  ctx.beginPath();
  ctx.arc(cx, oy + 18, 18, Math.PI, 0);
  ctx.bezierCurveTo(cx + 18, oy + 36, cx + 10, oy + 56, cx, oy + 64);
  ctx.bezierCurveTo(cx - 10, oy + 56, cx - 18, oy + 36, cx - 18, oy + 18);
  ctx.closePath();
  ctx.clip();

  ctx.fillStyle = COLOR_BOMB_GOLD_BAND;
  ctx.fillRect(ox, oy + 14, 36, 8);
  ctx.restore();
}

// ---------------------------------------------------------------------------
// SpriteFactory
// ---------------------------------------------------------------------------
export class SpriteFactory {
  /**
   * Call inside Phaser Scene preload(). Registers all textures.
   */
  static preload(scene: Phaser.Scene): void {
    SpriteFactory._registerLaunchers(scene);
    SpriteFactory._registerBombs(scene);
    SpriteFactory._registerProjectile(scene);
    SpriteFactory._registerExplosion(scene);
    SpriteFactory._registerBuildings(scene);
    SpriteFactory._registerBomber(scene);
    SpriteFactory._registerUI(scene);
    SpriteFactory._registerParticlesAndEffects(scene);
  }

  /**
   * Call inside Phaser Scene create(), AFTER preload() has run.
   * Registers all Phaser animations from the style guide Animations table.
   */
  static registerAnimations(scene: Phaser.Scene): void {
    // LAUNCHER_WRONG_FLASH — launcher_flash, frames 0–1, 12fps, repeat 2, no yoyo
    scene.anims.create({
      key: ANIM_KEYS.LAUNCHER_WRONG_FLASH,
      frames: scene.anims.generateFrameNumbers(SPRITE_KEYS.LAUNCHER_FLASH, { start: 0, end: 1 }),
      frameRate: 12,
      repeat: 2,
      yoyo: false,
    });

    // EXPLOSION_BURST — explosion, frames 0–5, 12fps, repeat 0, no yoyo
    scene.anims.create({
      key: ANIM_KEYS.EXPLOSION_BURST,
      frames: scene.anims.generateFrameNumbers(SPRITE_KEYS.EXPLOSION, { start: 0, end: 5 }),
      frameRate: 12,
      repeat: 0,
      yoyo: false,
    });

    // BUILDING_HIT — building_damaged, frames 0–2, 8fps, repeat 0, no yoyo
    scene.anims.create({
      key: ANIM_KEYS.BUILDING_HIT,
      frames: scene.anims.generateFrameNumbers(SPRITE_KEYS.BUILDING_DAMAGED, { start: 0, end: 2 }),
      frameRate: 8,
      repeat: 0,
      yoyo: false,
    });

    // BOMBER_FLY — bomber, frames 0–3, 8fps, repeat -1 (loop), no yoyo
    scene.anims.create({
      key: ANIM_KEYS.BOMBER_FLY,
      frames: scene.anims.generateFrameNumbers(SPRITE_KEYS.BOMBER, { start: 0, end: 3 }),
      frameRate: 8,
      repeat: -1,
      yoyo: false,
    });

    // FIREWORK_POP — firework_burst, frames 0–4, 16fps, repeat 0, no yoyo
    scene.anims.create({
      key: ANIM_KEYS.FIREWORK_POP,
      frames: scene.anims.generateFrameNumbers(SPRITE_KEYS.FIREWORK_BURST, { start: 0, end: 4 }),
      frameRate: 16,
      repeat: 0,
      yoyo: false,
    });

    // REBUILD_CRANE_LIFT — rebuild_crane, frames 0–3, 5fps, repeat -1, yoyo true
    scene.anims.create({
      key: ANIM_KEYS.REBUILD_CRANE_LIFT,
      frames: scene.anims.generateFrameNumbers(SPRITE_KEYS.REBUILD_CRANE, { start: 0, end: 3 }),
      frameRate: 5,
      repeat: -1,
      yoyo: true,
    });
  }

  // ---------------------------------------------------------------------------
  // Private: Launcher sprites
  // ---------------------------------------------------------------------------
  private static _registerLaunchers(scene: Phaser.Scene): void {
    // Single-frame launchers: LAUNCHER_ORANGE, LAUNCHER_TEAL, LAUNCHER_MAGENTA
    const launcherDefs: Array<{ key: string; color: string }> = [
      { key: SPRITE_KEYS.LAUNCHER_ORANGE,  color: COLOR_LAUNCHER_ORANGE },
      { key: SPRITE_KEYS.LAUNCHER_TEAL,    color: COLOR_LAUNCHER_TEAL },
      { key: SPRITE_KEYS.LAUNCHER_MAGENTA, color: COLOR_LAUNCHER_MAGENTA },
    ];

    for (const def of launcherDefs) {
      const canvas = makeCanvas(80, 90);
      const ctx = ctx2d(canvas);
      drawLauncherShape(ctx, 0, 0, def.color);
      scene.textures.addCanvas(def.key, canvas);
    }

    // LAUNCHER_FLASH: 2-frame sprite sheet (160×90)
    // Frame 0: body filled COLOR_WRONG_FLASH
    // Frame 1: normal launcher color (orange, as the base flash launcher)
    const flashCanvas = makeCanvas(160, 90);
    const flashCtx = ctx2d(flashCanvas);
    // Frame 0 — wrong flash (red)
    drawLauncherShape(flashCtx, 0, 0, COLOR_WRONG_FLASH);
    // Frame 1 — normal orange
    drawLauncherShape(flashCtx, 80, 0, COLOR_LAUNCHER_ORANGE);

    addSheetFromCanvas(scene, SPRITE_KEYS.LAUNCHER_FLASH, flashCanvas, 80, 90);
  }

  // ---------------------------------------------------------------------------
  // Private: Bomb sprites
  // ---------------------------------------------------------------------------
  private static _registerBombs(scene: Phaser.Scene): void {
    const bombDefs: Array<{ key: string; color: string }> = [
      { key: SPRITE_KEYS.BOMB_ORANGE,  color: COLOR_BOMB_ORANGE },
      { key: SPRITE_KEYS.BOMB_TEAL,    color: COLOR_BOMB_TEAL },
      { key: SPRITE_KEYS.BOMB_MAGENTA, color: COLOR_BOMB_MAGENTA },
    ];

    for (const def of bombDefs) {
      const canvas = makeCanvas(36, 64);
      const ctx = ctx2d(canvas);
      drawBombShape(ctx, 0, 0, def.color);
      scene.textures.addCanvas(def.key, canvas);
    }
  }

  // ---------------------------------------------------------------------------
  // Private: Projectile (counter-missile)
  // ---------------------------------------------------------------------------
  private static _registerProjectile(scene: Phaser.Scene): void {
    // 24×48px. Rounded nose rocket, red body, yellow band at 60% height, teal delta fins at base.
    const canvas = makeCanvas(24, 48);
    const ctx = ctx2d(canvas);

    const cx = 12; // horizontal center

    // --- Delta fins at base (draw first so body overlaps) ---
    // Two flat delta fins: each 10px wide × 14px tall at the base
    // Left fin: x=0, y=34 to y=48
    ctx.save();
    ctx.fillStyle = COLOR_PROJECTILE_FIN;
    // Left fin — triangle/trapezoid
    ctx.beginPath();
    ctx.moveTo(0, 48);        // outer bottom-left
    ctx.lineTo(10, 48);       // inner bottom
    ctx.lineTo(cx, 34);       // top where it meets body
    ctx.lineTo(0, 38);        // outer top-left
    ctx.closePath();
    ctx.fill();

    // Right fin — mirror
    ctx.beginPath();
    ctx.moveTo(24, 48);       // outer bottom-right
    ctx.lineTo(14, 48);       // inner bottom
    ctx.lineTo(cx, 34);       // top where it meets body
    ctx.lineTo(24, 38);       // outer top-right
    ctx.closePath();
    ctx.fill();
    ctx.restore();

    // --- Body: rounded nose rocket ---
    // Full body rect with rounded top
    ctx.save();
    ctx.beginPath();
    // Rounded nose: semicircle at top, radius 12 (full width)
    ctx.arc(cx, 12, 12, Math.PI, 0);
    // Right side down to base
    ctx.lineTo(cx + 12, 46);
    // Bottom across
    ctx.lineTo(cx - 12, 46);
    ctx.closePath();
    ctx.fillStyle = COLOR_PROJECTILE_BODY;
    ctx.fill();
    ctx.restore();

    // --- Yellow band: 8px tall at 60% of height (y=28 to y=36) ---
    ctx.save();
    // Clip to body shape
    ctx.beginPath();
    ctx.arc(cx, 12, 12, Math.PI, 0);
    ctx.lineTo(cx + 12, 46);
    ctx.lineTo(cx - 12, 46);
    ctx.closePath();
    ctx.clip();
    ctx.fillStyle = COLOR_PROJECTILE_BAND;
    ctx.fillRect(0, 28, 24, 8);
    ctx.restore();

    scene.textures.addCanvas(SPRITE_KEYS.PROJECTILE, canvas);
  }

  // ---------------------------------------------------------------------------
  // Private: Explosion sprite sheet (6 frames, 960×160)
  // ---------------------------------------------------------------------------
  private static _registerExplosion(scene: Phaser.Scene): void {
    // 6 frames × 160px wide = 960px total canvas width, 160px tall
    const FRAME_W = 160;
    const FRAME_H = 160;
    const FRAMES = 6;
    const canvas = makeCanvas(FRAME_W * FRAMES, FRAME_H);
    const ctx = ctx2d(canvas);

    // Frame parameters from style guide:
    // Frame 0: core radius 16, ray length 56, 3 smoke puffs at 24px
    // Frames 1–4: core +6/frame, rays +8/frame, smoke drift +6/frame
    // Frame 5: fade to transparent

    for (let f = 0; f < FRAMES; f++) {
      const ox = f * FRAME_W;
      const oy = 0;
      const cx = ox + 80;
      const cy = oy + 80;

      if (f === 5) {
        // Frame 5: transparent (everything faded out) — leave blank
        continue;
      }

      const coreRadius = 16 + f * 6;
      const rayLength = 56 + f * 8;
      const smokeOffset = f * 6;
      const alpha = 1.0 - f * 0.15; // slight fade through frames

      ctx.save();
      ctx.globalAlpha = alpha;

      // --- Spike rays (8 spikes) ---
      const NUM_RAYS = 8;
      ctx.save();
      ctx.fillStyle = COLOR_EXPLOSION_RAY;
      for (let i = 0; i < NUM_RAYS; i++) {
        const angle = (i / NUM_RAYS) * Math.PI * 2;
        const tipX = cx + Math.cos(angle) * (coreRadius + rayLength);
        const tipY = cy + Math.sin(angle) * (coreRadius + rayLength);
        // Base of the spike — two points either side of center
        const perpAngle = angle + Math.PI / 2;
        const baseWidth = 8 - f;  // spikes narrow slightly as they expand
        const b1x = cx + Math.cos(perpAngle) * baseWidth;
        const b1y = cy + Math.sin(perpAngle) * baseWidth;
        const b2x = cx - Math.cos(perpAngle) * baseWidth;
        const b2y = cy - Math.sin(perpAngle) * baseWidth;

        ctx.beginPath();
        ctx.moveTo(tipX, tipY);
        ctx.lineTo(b1x, b1y);
        ctx.lineTo(b2x, b2y);
        ctx.closePath();
        ctx.fill();
      }
      ctx.restore();

      // --- Mid-ring (COLOR_EXPLOSION_OUTER) between core and rays ---
      ctx.save();
      const midRadius = coreRadius + 10;
      ctx.beginPath();
      ctx.arc(cx, cy, midRadius, 0, Math.PI * 2);
      ctx.fillStyle = COLOR_EXPLOSION_OUTER;
      ctx.fill();
      ctx.restore();

      // --- Core (COLOR_EXPLOSION_CORE) ---
      ctx.save();
      ctx.beginPath();
      ctx.arc(cx, cy, coreRadius, 0, Math.PI * 2);
      ctx.fillStyle = COLOR_EXPLOSION_CORE;
      ctx.fill();
      ctx.restore();

      // --- Smoke puffs (3 puffs at 10, 4, 8 o'clock positions) ---
      // Clock angles: 10 o'clock ≈ -60°, 4 o'clock ≈ 120°, 8 o'clock ≈ 240°-ish → 210°
      const smokeAngles = [
        -60  * (Math.PI / 180),   // 10 o'clock
        120  * (Math.PI / 180),   // 4 o'clock
        210  * (Math.PI / 180),   // 8 o'clock
      ];
      const smokeBaseRadius = coreRadius + 20 + smokeOffset;
      const smokeSize = 24 + f * 4;
      const smokeAlpha = Math.max(0, 0.85 - f * 0.18);

      ctx.save();
      ctx.fillStyle = COLOR_SMOKE;
      for (const angle of smokeAngles) {
        const sx = cx + Math.cos(angle) * smokeBaseRadius;
        const sy = cy + Math.sin(angle) * smokeBaseRadius;
        ctx.globalAlpha = alpha * smokeAlpha;
        ctx.beginPath();
        ctx.arc(sx, sy, smokeSize * 0.5, 0, Math.PI * 2);
        ctx.fill();
        // Second smaller puff offset slightly
        ctx.beginPath();
        ctx.arc(sx + smokeSize * 0.25, sy - smokeSize * 0.2, smokeSize * 0.35, 0, Math.PI * 2);
        ctx.fill();
      }
      ctx.restore();

      ctx.restore(); // globalAlpha
    }

    addSheetFromCanvas(scene, SPRITE_KEYS.EXPLOSION, canvas, FRAME_W, FRAME_H);
  }

  // ---------------------------------------------------------------------------
  // Private: Building sprites
  // ---------------------------------------------------------------------------
  private static _registerBuildings(scene: Phaser.Scene): void {
    SpriteFactory._registerBuildingIntactA(scene);
    SpriteFactory._registerBuildingIntactB(scene);
    SpriteFactory._registerBuildingIntactC(scene);
    SpriteFactory._registerBuildingDamaged(scene);
    SpriteFactory._registerBuildingDestroyed(scene);
  }

  private static _registerBuildingIntactA(scene: Phaser.Scene): void {
    // 48×96px, COLOR_BUILDING_CORAL, 3×3 window grid (8×8px, 6px gap)
    const canvas = makeCanvas(48, 96);
    const ctx = ctx2d(canvas);

    ctx.fillStyle = COLOR_BUILDING_CORAL;
    ctx.fillRect(0, 0, 48, 96);

    // 3×3 window grid: total grid width = 3*8 + 2*6 = 36px, height = 3*8 + 2*6 = 36px
    // Center in 48×96: start x = (48-36)/2 = 6, start y = (96-36)/2 = 30
    ctx.fillStyle = COLOR_WINDOW;
    const startX = 6;
    const startY = 18; // shifted up slightly for visual weight
    for (let row = 0; row < 3; row++) {
      for (let col = 0; col < 3; col++) {
        ctx.fillRect(startX + col * 14, startY + row * 14, 8, 8);
      }
    }

    scene.textures.addCanvas(SPRITE_KEYS.BUILDING_INTACT_A, canvas);
  }

  private static _registerBuildingIntactB(scene: Phaser.Scene): void {
    // 64×80px, COLOR_BUILDING_BLUE, 2×3 window grid
    const canvas = makeCanvas(64, 80);
    const ctx = ctx2d(canvas);

    ctx.fillStyle = COLOR_BUILDING_BLUE;
    ctx.fillRect(0, 0, 64, 80);

    // 2×3 window grid (2 cols, 3 rows): width = 2*8 + 1*6 = 22, height = 3*8 + 2*6 = 36
    // Center x: (64-22)/2 = 21, center y: (80-36)/2 = 22
    ctx.fillStyle = COLOR_WINDOW;
    const startX = 21;
    const startY = 16;
    for (let row = 0; row < 3; row++) {
      for (let col = 0; col < 2; col++) {
        ctx.fillRect(startX + col * 14, startY + row * 14, 8, 8);
      }
    }

    scene.textures.addCanvas(SPRITE_KEYS.BUILDING_INTACT_B, canvas);
  }

  private static _registerBuildingIntactC(scene: Phaser.Scene): void {
    // 40×56px, COLOR_BUILDING_PEACH, 2×2 window grid
    const canvas = makeCanvas(40, 56);
    const ctx = ctx2d(canvas);

    ctx.fillStyle = COLOR_BUILDING_PEACH;
    ctx.fillRect(0, 0, 40, 56);

    // 2×2 window grid: width = 2*8 + 1*6 = 22, height = 2*8 + 1*6 = 22
    // Center x: (40-22)/2 = 9, center y: (56-22)/2 = 17
    ctx.fillStyle = COLOR_WINDOW;
    const startX = 9;
    const startY = 12;
    for (let row = 0; row < 2; row++) {
      for (let col = 0; col < 2; col++) {
        ctx.fillRect(startX + col * 14, startY + row * 14, 8, 8);
      }
    }

    scene.textures.addCanvas(SPRITE_KEYS.BUILDING_INTACT_C, canvas);
  }

  private static _registerBuildingDamaged(scene: Phaser.Scene): void {
    // 3-frame sprite sheet: 192×96px
    // Frame 0: intact building (type B — blue, 64×96 normalized)
    // Frame 1: cracks + debris particles flying
    // Frame 2: leaning 8deg, wider crack, smoke puff rising
    const FRAME_W = 64;
    const FRAME_H = 96;
    const canvas = makeCanvas(FRAME_W * 3, FRAME_H);
    const ctx = ctx2d(canvas);

    // ── Frame 0: intact (coral building with windows, as "random a/b/c" — use coral) ──
    {
      const ox = 0;
      ctx.fillStyle = COLOR_BUILDING_CORAL;
      ctx.fillRect(ox, 0, FRAME_W, FRAME_H);
      ctx.fillStyle = COLOR_WINDOW;
      for (let row = 0; row < 3; row++) {
        for (let col = 0; col < 2; col++) {
          ctx.fillRect(ox + 14 + col * 14, 16 + row * 14, 8, 8);
        }
      }
    }

    // ── Frame 1: diagonal crack + 3 debris particles ──
    {
      const ox = FRAME_W;
      // Base building
      ctx.fillStyle = COLOR_BUILDING_CORAL;
      ctx.fillRect(ox, 0, FRAME_W, FRAME_H);
      ctx.fillStyle = COLOR_WINDOW;
      for (let row = 0; row < 3; row++) {
        for (let col = 0; col < 2; col++) {
          ctx.fillRect(ox + 14 + col * 14, 16 + row * 14, 8, 8);
        }
      }
      // Diagonal crack bisecting face
      ctx.save();
      ctx.strokeStyle = COLOR_CRACK;
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.moveTo(ox + 10, 0);
      ctx.lineTo(ox + 30, 40);
      ctx.lineTo(ox + 20, 70);
      ctx.lineTo(ox + 40, FRAME_H);
      ctx.stroke();
      // Second thinner crack
      ctx.lineWidth = 1.5;
      ctx.beginPath();
      ctx.moveTo(ox + 45, 10);
      ctx.lineTo(ox + 38, 45);
      ctx.lineTo(ox + 50, 75);
      ctx.stroke();
      ctx.restore();

      // 3 brick debris particles flying (8×5px rectangles, COLOR_DEBRIS)
      ctx.save();
      ctx.fillStyle = COLOR_DEBRIS;
      // Debris at edges flying outward
      ctx.fillRect(ox - 6, 8, 8, 5);   // top-left flying out
      ctx.fillRect(ox + 62, 22, 8, 5); // top-right flying out
      ctx.fillRect(ox + 58, 50, 8, 5); // right side
      ctx.restore();
    }

    // ── Frame 2: leaning 8deg, wider crack, smoke puff ──
    {
      const ox = FRAME_W * 2;
      ctx.save();
      // Translate to building center-bottom for rotation pivot
      ctx.translate(ox + FRAME_W / 2, FRAME_H);
      ctx.rotate(8 * (Math.PI / 180));
      ctx.translate(-(FRAME_W / 2), -FRAME_H);

      // Building base
      ctx.fillStyle = COLOR_BUILDING_CORAL;
      ctx.fillRect(0, 0, FRAME_W, FRAME_H);
      ctx.fillStyle = COLOR_WINDOW;
      for (let row = 0; row < 3; row++) {
        for (let col = 0; col < 2; col++) {
          ctx.fillRect(14 + col * 14, 16 + row * 14, 8, 8);
        }
      }
      // Wider crack
      ctx.strokeStyle = COLOR_CRACK;
      ctx.lineWidth = 5;
      ctx.beginPath();
      ctx.moveTo(8, 0);
      ctx.lineTo(28, 38);
      ctx.lineTo(16, 68);
      ctx.lineTo(38, FRAME_H);
      ctx.stroke();
      ctx.restore();

      // Smoke puff rising from top (not rotated)
      ctx.save();
      ctx.fillStyle = COLOR_SMOKE;
      ctx.globalAlpha = 0.75;
      ctx.beginPath();
      ctx.arc(ox + 32, -8, 16, 0, Math.PI * 2);
      ctx.fill();
      ctx.beginPath();
      ctx.arc(ox + 44, -18, 12, 0, Math.PI * 2);
      ctx.fill();
      ctx.restore();
    }

    addSheetFromCanvas(scene, SPRITE_KEYS.BUILDING_DAMAGED, canvas, FRAME_W, FRAME_H);
  }

  private static _registerBuildingDestroyed(scene: Phaser.Scene): void {
    // 48×40px: crumbled rubble pile, irregular low silhouette ≤40px tall
    // COLOR_BUILDING_CORAL / BLUE / PEACH fragments, 2–3 smoke wisps
    const canvas = makeCanvas(48, 40);
    const ctx = ctx2d(canvas);

    // Rubble base: irregular mound
    ctx.save();
    ctx.beginPath();
    ctx.moveTo(0, 40);
    ctx.lineTo(0, 28);
    ctx.lineTo(6, 22);
    ctx.lineTo(12, 26);
    ctx.lineTo(18, 14);
    ctx.lineTo(24, 20);
    ctx.lineTo(30, 10);
    ctx.lineTo(36, 18);
    ctx.lineTo(42, 24);
    ctx.lineTo(48, 28);
    ctx.lineTo(48, 40);
    ctx.closePath();
    ctx.fillStyle = COLOR_BUILDING_CORAL;
    ctx.fill();
    ctx.restore();

    // Rubble fragments in different building colors
    const fragments: Array<{ x: number; y: number; w: number; h: number; color: string }> = [
      { x: 2,  y: 20, w: 10, h: 8, color: COLOR_BUILDING_BLUE },
      { x: 16, y: 16, w: 8,  h: 6, color: COLOR_BUILDING_PEACH },
      { x: 30, y: 22, w: 12, h: 7, color: COLOR_BUILDING_BLUE },
      { x: 8,  y: 28, w: 8,  h: 5, color: COLOR_BUILDING_CORAL },
      { x: 36, y: 26, w: 6,  h: 8, color: COLOR_BUILDING_PEACH },
    ];
    for (const fr of fragments) {
      ctx.fillStyle = fr.color;
      ctx.fillRect(fr.x, fr.y, fr.w, fr.h);
    }

    // 2–3 smoke wisp circles (20px, COLOR_SMOKE, 40% opacity)
    ctx.save();
    ctx.fillStyle = COLOR_SMOKE;
    ctx.globalAlpha = 0.4;
    ctx.beginPath();
    ctx.arc(10, 12, 10, 0, Math.PI * 2);
    ctx.fill();
    ctx.beginPath();
    ctx.arc(28, 6, 8, 0, Math.PI * 2);
    ctx.fill();
    ctx.beginPath();
    ctx.arc(40, 14, 7, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();

    scene.textures.addCanvas(SPRITE_KEYS.BUILDING_DESTROYED, canvas);
  }

  // ---------------------------------------------------------------------------
  // Private: Bomber (128×56, 4 frames = 512×56)
  // ---------------------------------------------------------------------------
  private static _registerBomber(scene: Phaser.Scene): void {
    const FRAME_W = 128;
    const FRAME_H = 56;
    const FRAMES = 4;
    const canvas = makeCanvas(FRAME_W * FRAMES, FRAME_H);
    const ctx = ctx2d(canvas);

    // Propeller blade angles per frame: 0°, 30°, 60°, 90°
    const propAngles = [0, 30, 60, 90];

    for (let f = 0; f < FRAMES; f++) {
      const ox = f * FRAME_W;
      const oy = 0;
      SpriteFactory._drawBomberFrame(ctx, ox, oy, propAngles[f]);
    }

    addSheetFromCanvas(scene, SPRITE_KEYS.BOMBER, canvas, FRAME_W, FRAME_H);
  }

  private static _drawBomberFrame(
    ctx: CanvasRenderingContext2D,
    ox: number, oy: number,
    propAngleDeg: number
  ): void {
    // Side-view flat aircraft facing right.
    // Canvas area: 128×56. Fuselage centered vertically around y=28.
    const propAngle = propAngleDeg * (Math.PI / 180);

    // ── Wings: tapered trapezoid, 128px span, drawn first (behind fuselage) ──
    // Upper wing: top edge at y=8, bottom edge at y=20, full span
    ctx.save();
    ctx.fillStyle = COLOR_BOMBER_WING;
    ctx.strokeStyle = COLOR_BOMBER_OUTLINE;
    ctx.lineWidth = 2.5;
    // Upper wing trapezoid
    ctx.beginPath();
    ctx.moveTo(ox + 12, oy + 20);  // left inboard (near fuselage bottom-left of wing root)
    ctx.lineTo(ox + 0,  oy + 14);  // left tip
    ctx.lineTo(ox + 128, oy + 12); // right tip
    ctx.lineTo(ox + 110, oy + 22); // right inboard
    ctx.closePath();
    ctx.fill();
    ctx.stroke();

    // Lower wing / stabilizer — narrower, further back
    ctx.beginPath();
    ctx.moveTo(ox + 80, oy + 32);   // left inboard
    ctx.lineTo(ox + 60, oy + 38);   // left tip
    ctx.lineTo(ox + 128, oy + 36);  // right tip
    ctx.lineTo(ox + 118, oy + 30);  // right inboard
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.restore();

    // ── Fuselage: rounded rectangle 96×24px, centered at (64, 28) ──
    ctx.save();
    ctx.fillStyle = COLOR_BOMBER_FUSELAGE;
    ctx.strokeStyle = COLOR_BOMBER_OUTLINE;
    ctx.lineWidth = 3;
    roundRect(ctx, ox + 10, oy + 16, 96, 24, 8);
    ctx.fill();
    ctx.stroke();
    ctx.restore();

    // ── Tail fin: right-side vertical rectangle 20×28px ──
    ctx.save();
    ctx.fillStyle = COLOR_BOMBER_TAIL;
    ctx.strokeStyle = COLOR_BOMBER_OUTLINE;
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.moveTo(ox + 100, oy + 16);  // top-left of tail
    ctx.lineTo(ox + 118, oy + 4);   // top-right (taller fin)
    ctx.lineTo(ox + 122, oy + 4);   // fin top edge
    ctx.lineTo(ox + 122, oy + 16);  // fin base meets fuselage
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
    ctx.restore();

    // ── Cockpit: 3-pane rounded window 24×14px near nose ──
    ctx.save();
    ctx.fillStyle = COLOR_BOMBER_COCKPIT;
    ctx.strokeStyle = COLOR_BOMBER_OUTLINE;
    ctx.lineWidth = 2;
    roundRect(ctx, ox + 16, oy + 17, 24, 13, 4);
    ctx.fill();
    ctx.stroke();
    // Window pane dividers
    ctx.strokeStyle = COLOR_BOMBER_OUTLINE;
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(ox + 24, oy + 17);
    ctx.lineTo(ox + 24, oy + 30);
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(ox + 32, oy + 17);
    ctx.lineTo(ox + 32, oy + 30);
    ctx.stroke();
    ctx.restore();

    // ── Engine nacelles: pill shape 18×10px under wings ──
    // Two nacelles: one at ~x=32, one at ~x=80, both at y=40
    const nacellePosX = [ox + 28, ox + 76];
    for (const nx of nacellePosX) {
      ctx.save();
      ctx.fillStyle = COLOR_BOMBER_NACELLE;
      ctx.strokeStyle = COLOR_BOMBER_OUTLINE;
      ctx.lineWidth = 2;
      roundRect(ctx, nx, oy + 38, 18, 10, 5);
      ctx.fill();
      ctx.stroke();
      ctx.restore();

      // ── Propeller spinner on each nacelle ──
      const spinnerX = nx + 2;
      const spinnerY = oy + 43;
      ctx.save();
      ctx.translate(spinnerX, spinnerY);
      ctx.rotate(propAngle);
      ctx.strokeStyle = COLOR_BOMBER_OUTLINE;
      ctx.lineWidth = 2;
      // 3 blades, 120° apart
      for (let blade = 0; blade < 3; blade++) {
        const bladeAngle = blade * (Math.PI * 2 / 3);
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.lineTo(Math.cos(bladeAngle) * 6, Math.sin(bladeAngle) * 6);
        ctx.stroke();
      }
      // Center hub
      ctx.beginPath();
      ctx.arc(0, 0, 2, 0, Math.PI * 2);
      ctx.fillStyle = COLOR_BOMBER_OUTLINE;
      ctx.fill();
      ctx.restore();
    }
  }

  // ---------------------------------------------------------------------------
  // Private: UI sprites
  // ---------------------------------------------------------------------------
  private static _registerUI(scene: Phaser.Scene): void {
    SpriteFactory._registerCRTFrame(scene);
    SpriteFactory._registerGroundLine(scene);
    SpriteFactory._registerHUDBar(scene);
    SpriteFactory._registerScorePop(scene);
    SpriteFactory._registerStreakBadge(scene);
  }

  private static _registerCRTFrame(scene: Phaser.Scene): void {
    // 800×520px: rounded rect border only (no fill).
    // Stroke 14px, COLOR_CRT_BEZEL, corner radius 40px.
    // Bevel: inner 2px #E0B050, outer 2px #A07820.
    const canvas = makeCanvas(800, 520);
    const ctx = ctx2d(canvas);

    // Outer bevel (darker) — path starts at 9px so 18px stroke stays within canvas
    ctx.strokeStyle = COLOR_CRT_BEVEL_DARK;
    ctx.lineWidth = 18;
    roundRect(ctx, 9, 9, 782, 502, 42);
    ctx.stroke();

    // Main bezel
    ctx.strokeStyle = COLOR_CRT_BEZEL;
    ctx.lineWidth = 14;
    roundRect(ctx, 21, 21, 758, 478, 40);
    ctx.stroke();

    // Inner bevel (lighter)
    ctx.strokeStyle = COLOR_CRT_BEVEL_LIGHT;
    ctx.lineWidth = 2;
    roundRect(ctx, 28, 28, 744, 464, 38);
    ctx.stroke();

    scene.textures.addCanvas(SPRITE_KEYS.CRT_FRAME, canvas);
  }

  private static _registerGroundLine(scene: Phaser.Scene): void {
    // 760×4px solid fill, COLOR_GROUND_LINE
    const canvas = makeCanvas(760, 4);
    const ctx = ctx2d(canvas);
    ctx.fillStyle = COLOR_GROUND_LINE;
    ctx.fillRect(0, 0, 760, 4);
    scene.textures.addCanvas(SPRITE_KEYS.GROUND_LINE, canvas);
  }

  private static _registerHUDBar(scene: Phaser.Scene): void {
    // 800×40px solid fill, COLOR_HUD_BG, no border
    const canvas = makeCanvas(800, 40);
    const ctx = ctx2d(canvas);
    ctx.fillStyle = COLOR_HUD_BG;
    ctx.fillRect(0, 0, 800, 40);
    scene.textures.addCanvas(SPRITE_KEYS.HUD_BAR, canvas);
  }

  private static _registerScorePop(scene: Phaser.Scene): void {
    // 60×30px text sprite (placeholder graphic — actual text rendered at runtime by GameScene)
    // Draw "+10" as a representative visual using TEXT_SCORE_POP style
    const canvas = makeCanvas(60, 30);
    const ctx = ctx2d(canvas);
    ctx.font = 'bold 26px Georgia, "Times New Roman", serif';
    ctx.fillStyle = COLOR_EXPLOSION_OUTER;
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('+10', 30, 15);
    scene.textures.addCanvas(SPRITE_KEYS.SCORE_POP, canvas);
  }

  private static _registerStreakBadge(scene: Phaser.Scene): void {
    // 200×36px pill-shaped banner: COLOR_CRT_BEZEL fill, 18px corner radius, white text centered
    const canvas = makeCanvas(200, 36);
    const ctx = ctx2d(canvas);
    roundRect(ctx, 0, 0, 200, 36, 18);
    ctx.fillStyle = COLOR_CRT_BEZEL;
    ctx.fill();
    ctx.font = 'bold 20px "Courier New", Courier, monospace';
    ctx.fillStyle = '#FFFFFF';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText('SHARP SHOOTER!', 100, 18);
    scene.textures.addCanvas(SPRITE_KEYS.STREAK_BADGE, canvas);
  }

  // ---------------------------------------------------------------------------
  // Private: Particles and effects
  // ---------------------------------------------------------------------------
  private static _registerParticlesAndEffects(scene: Phaser.Scene): void {
    SpriteFactory._registerTrajectoryTrailDot(scene);
    SpriteFactory._registerFireworkBurst(scene);
    SpriteFactory._registerRebuildCrane(scene);
  }

  private static _registerTrajectoryTrailDot(scene: Phaser.Scene): void {
    // 6×10px rounded rectangle dash, COLOR_TRAIL, corner radius 3px
    const canvas = makeCanvas(6, 10);
    const ctx = ctx2d(canvas);
    roundRect(ctx, 0, 0, 6, 10, 3);
    ctx.fillStyle = COLOR_TRAIL;
    ctx.fill();
    scene.textures.addCanvas(SPRITE_KEYS.TRAJECTORY_TRAIL_DOT, canvas);
  }

  private static _registerFireworkBurst(scene: Phaser.Scene): void {
    // 5-frame sprite sheet: 400×80px (5 × 80×80)
    // Frame 0: 6 lines radiating from center, 2px, COLOR_CITY_CELEBRATE
    // Frames 1–4: lines expand outward and fade
    const FRAME_W = 80;
    const FRAME_H = 80;
    const FRAMES = 5;
    const canvas = makeCanvas(FRAME_W * FRAMES, FRAME_H);
    const ctx = ctx2d(canvas);

    for (let f = 0; f < FRAMES; f++) {
      const ox = f * FRAME_W;
      const cx = ox + 40;
      const cy = 40;

      const lineLength = 12 + f * 12; // expand per frame
      const alpha = 1.0 - f * 0.22;

      ctx.save();
      ctx.globalAlpha = alpha;
      ctx.strokeStyle = COLOR_CITY_CELEBRATE;
      ctx.lineWidth = 2;

      // 6 lines at 0°, 60°, 120°, 180°, 240°, 300°
      for (let i = 0; i < 6; i++) {
        const angle = (i / 6) * Math.PI * 2;
        const startR = f * 4; // lines start further from center as they expand
        ctx.beginPath();
        ctx.moveTo(cx + Math.cos(angle) * startR, cy + Math.sin(angle) * startR);
        ctx.lineTo(cx + Math.cos(angle) * (startR + lineLength), cy + Math.sin(angle) * (startR + lineLength));
        ctx.stroke();
      }

      // Add sparkle dots at tips in later frames
      if (f > 1) {
        ctx.fillStyle = COLOR_CITY_CELEBRATE;
        for (let i = 0; i < 6; i++) {
          const angle = (i / 6) * Math.PI * 2;
          const tipR = f * 4 + lineLength;
          ctx.beginPath();
          ctx.arc(cx + Math.cos(angle) * tipR, cy + Math.sin(angle) * tipR, 2, 0, Math.PI * 2);
          ctx.fill();
        }
      }

      ctx.restore();
    }

    addSheetFromCanvas(scene, SPRITE_KEYS.FIREWORK_BURST, canvas, FRAME_W, FRAME_H);
  }

  private static _registerRebuildCrane(scene: Phaser.Scene): void {
    // 4-frame sprite sheet: 128×48px (4 × 32×48)
    // Yellow crane: vertical mast 4×40px, horizontal jib 28×4px at top, cable with hook
    // Frames 0–3: hook bobs up 0/4/8/4 px
    const FRAME_W = 32;
    const FRAME_H = 48;
    const FRAMES = 4;
    const hookOffsets = [0, 4, 8, 4]; // hook Y offset per frame (upward movement)
    const canvas = makeCanvas(FRAME_W * FRAMES, FRAME_H);
    const ctx = ctx2d(canvas);

    for (let f = 0; f < FRAMES; f++) {
      const ox = f * FRAME_W;
      const hookOffset = hookOffsets[f];

      ctx.save();
      ctx.fillStyle = COLOR_CRANE_YELLOW;
      ctx.strokeStyle = COLOR_CRANE_YELLOW;

      // Vertical mast: 4×40px, at x=14, y=4
      ctx.fillRect(ox + 14, 4, 4, 40);

      // Horizontal jib: 28×4px at top (y=4)
      ctx.fillRect(ox + 2, 4, 28, 4);

      // Small diagonal brace from mast to end of jib
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(ox + 16, 12);
      ctx.lineTo(ox + 28, 8);
      ctx.stroke();

      // Cable: 2px line from jib end downward
      ctx.lineWidth = 2;
      const cableTopY = 8;
      const cableEndY = 34 - hookOffset; // hook bobs up
      ctx.beginPath();
      ctx.moveTo(ox + 28, cableTopY);
      ctx.lineTo(ox + 28, cableEndY);
      ctx.stroke();

      // Hook: small J-shape at cable end
      ctx.lineWidth = 2;
      ctx.beginPath();
      ctx.moveTo(ox + 28, cableEndY);
      ctx.lineTo(ox + 28, cableEndY + 5);
      ctx.arc(ox + 26, cableEndY + 5, 2, 0, Math.PI, false);
      ctx.stroke();

      ctx.restore();
    }

    addSheetFromCanvas(scene, SPRITE_KEYS.REBUILD_CRANE, canvas, FRAME_W, FRAME_H);
  }
}
